[package]
name = "kudi-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
clap = { workspace = true, features = ["derive"] }
